import Header from "./ui/components/header";

import "./ui/globals.css";
import { geistSans, geistMono } from "./ui/fonts";

export const metadata = {
  title: "Pablo Teixeira | Fullstack developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
